const fs=require('fs');
const app=fs.readFileSync('assets/app.js','utf8');
const css=fs.readFileSync('assets/styles.css','utf8');
const must=(x,msg)=>{if(!x)throw new Error(msg)};
const dashboard=app.slice(app.indexOf('function dashboardHTML()'),app.indexOf('function isSuppressedIntegrityArtifact'));
must(dashboard.includes('dashboard-v47'),'banded dashboard wrapper missing');
must(dashboard.includes('dashboard-briefing-band')&&dashboard.includes('dashboard-attention-band')&&dashboard.includes('dashboard-overview-band')&&dashboard.includes('dashboard-guidance-band'),'explicit page-owned dashboard bands missing');
must(dashboard.includes('dashboardStoryCardsHTML'),'priority insight missing');
must(dashboard.includes('truthfulRecentActivityHTML'),'recent activity missing');
must(dashboard.includes('todayActionsHTML')&&dashboard.includes('upcomingHTML'),'today/upcoming context missing');
must(dashboard.includes("repairs.length?reviewStatusHTML(repairs):''"),'clean integrity status must not consume dashboard space');
must(!dashboard.includes('thinkingHTML()'),'duplicate insight surface must not be rendered on dashboard');
must(dashboard.includes('healthGlanceHTML(4)'),'dashboard health snapshot must remain selective');
must(dashboard.includes('timelineSnapshotHTML'),'cross-domain timeline missing');
must(dashboard.includes('weeklyPlanHTML')&&dashboard.includes('coachHTML'),'fitness planning/coaching missing');
must(css.includes('.dashboard-attention-band')&&css.includes('.dashboard-overview-band'),'desktop band composition rules missing');
must(css.includes('.dashboard-v47 .recent-activity-scroll{max-height:none!important;overflow:visible!important'),'dashboard recent activity must not create nested vertical scrolling');
must(css.includes('@media(max-width:760px)'),'responsive dashboard band layout missing');
console.log('dashboard banded UX acceptance checks passed');
