const fs=require('fs');
const app=fs.readFileSync('assets/app.js','utf8');
const css=fs.readFileSync('assets/desktop-dashboard.css','utf8');
const must=(x,msg)=>{if(!x)throw new Error(msg)};
const dashboard=app.slice(app.indexOf('function dashboardHTML()'),app.indexOf('function isSuppressedIntegrityArtifact'));
must(dashboard.includes('dashboard-mockup-shell'),'mockup-authority dashboard wrapper missing');
must(dashboard.includes('mock-top-row')&&dashboard.includes('mock-main-row')&&dashboard.includes('mock-bottom-row'),'page-owned dashboard rows missing');
must(dashboard.includes('span-4')&&dashboard.includes('span-5')&&dashboard.includes('span-3'),'12-column region allocation missing');
must(dashboard.includes('truthfulRecentActivityHTML')&&dashboard.includes('dashboardInsightsCompactHTML'),'compact activity/insight surfaces missing');
must(dashboard.includes('dashboardStatusHTML')&&dashboard.includes('dashboardQuickActionsHTML')&&dashboard.includes('upcomingHTML'),'top briefing composition missing');
must(dashboard.includes('healthGlanceHTML(4)'),'selective health snapshot missing');
must(dashboard.includes('timelineSnapshotHTML')&&dashboard.includes('dashboardGoalsHTML'),'timeline/goals row missing');
must(dashboard.includes('weeklyPlanHTML')&&dashboard.includes('coachHTML'),'planning/coaching preserved');
must(css.includes('grid-template-columns:repeat(12,minmax(0,1fr))'),'12-column desktop grid missing');
must(css.includes('--zg:16px'),'shared gutter token missing');
must(css.includes('.dashboard-health-glance .metrics-row')&&css.includes('repeat(2,minmax(0,1fr))'),'2x2 health composition missing');
must(css.includes('.mock-insight-row')&&css.includes('.recent-activity-row'),'compact visual row styling missing');
must(css.includes('@media(max-width:1080px)')&&css.includes('@media(max-width:700px)'),'responsive fallback missing');
console.log('dashboard mockup-authority UX acceptance checks passed');
