const fs=require('fs');
const app=fs.readFileSync('assets/app.js','utf8');
const css=fs.readFileSync('assets/styles.css','utf8');
const must=(x,msg)=>{if(!x)throw new Error(msg)};
const dashboard=app.slice(app.indexOf('function dashboardHTML()'),app.indexOf('function isSuppressedIntegrityArtifact'));
must(dashboard.includes('dashboard-v3'),'v0.40 dashboard wrapper missing');
must(dashboard.includes('dashboardStoryCardsHTML'),'three-purpose story cards missing');
must(dashboard.includes('healthGlanceHTML'),'Health at a Glance missing');
must(dashboard.includes('weeklyPlanHTML'),'weekly dashboard planner missing');
must(dashboard.includes('coachHTML'),'Coach’s Eye missing');
must(dashboard.includes('trendPanelHTML'),'truthful trend panel missing');
must(dashboard.includes('truthfulRecentActivityHTML'),'truthful recent activity missing');
must(dashboard.includes('reviewStatusHTML'),'integrity review card missing');
must(css.includes('.dashboard-story-grid')&&css.includes('.dashboard-main-grid'),'desktop dashboard grid missing');
must(css.includes('@media(max-width:680px)'),'mobile dashboard layout missing');
console.log('dashboard v0.40 acceptance checks passed');
