const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');
const version=fs.readFileSync(path.join(root,'version.js'),'utf8');
const must=(x,m)=>{if(!x)throw new Error(m)};
must(version.includes("0.30.0"),'v0.30.0 metadata missing');
must(app.includes('id="mobileGymButton"'),'mobile Gym action missing');
must(app.includes('Log exercise or activity'),'fitness logging hierarchy missing');
must(app.includes('Enter one exercise or activity'),'single activity path missing');
must(app.includes('Start from routine'),'routine path missing');
must(app.includes('Repeat last workout'),'repeat path missing');
must(app.includes('id="conditionDate" type="date"'),'editable condition date missing');
must(app.includes('id="gymWorkoutDate" type="date"'),'editable mobile workout date missing');
must(app.includes('workout_routines'),'provider-backed routine preferences missing');
must(app.includes('custom_activities'),'provider-backed custom activity preferences missing');
must(!app.includes('Elapsed time'),'elapsed workout time should not be present');
must(css.includes('.mobile-gym-entry'),'mobile Gym styling missing');
console.log('v0.30 mobile workout-entry contract passed');
