const fs=require('fs');const assert=require('assert');
const app=fs.readFileSync('assets/app.js','utf8');const css=fs.readFileSync('assets/styles.css','utf8');
assert(app.includes('mobile-bottom-nav'));assert(app.includes('mobileMoreButton'));assert(css.includes('--nav-rail-width'));
assert(app.includes('NEXT SESSION'));assert(app.includes('PATTERNS'));assert(app.includes('One recommendation is shared'));
assert(app.includes('activityRecommendation(name,sessions)')||app.includes('function activityRecommendation'));
assert(app.includes("['overview','pattern-lab']")||app.includes("data-insights-view=\"pattern-lab\""));
const navStart=app.indexOf('function sidebarHTML');const navEnd=app.indexOf('function mobileBottomNavHTML');const nav=app.slice(navStart,navEnd);
assert(!nav.includes("['labs','Labs'"),'Labs must not be a top-level sidebar item');
assert(!nav.includes("['pattern-lab','Pattern Lab'"),'Pattern Lab must not be a top-level sidebar item');
assert(app.includes("zeke-user-profile"));assert(!app.includes('Good evening, Frank'));assert(!app.includes('Good morning, Frank'));
console.log('PASS navigation, shared coaching, profile, and Insights hierarchy');
