const fs=require('fs');const assert=require('assert');
const app=fs.readFileSync('assets/app.js','utf8');const css=fs.readFileSync('assets/styles.css','utf8');
assert(app.includes('mobile-bottom-nav'));assert(app.includes('mobileMoreButton'));assert(css.includes('--nav-rail-width'));
const coach=app.slice(app.indexOf('function coachHTML()'),app.indexOf('function openQuestions()'));
assert(coach.includes("WHAT SHOULD I DO?"));assert(coach.includes('Nothing needs your attention today.'));assert(!coach.includes('PATTERNS'));assert(!coach.includes('NEXT SESSION'));
assert(app.includes('function activityRecommendation'));
assert(app.includes('data-insights-view="pattern-lab"'));
const nav=app.slice(app.indexOf('function navHTML()'),app.indexOf('function openGlobalSearchModal'));
for(const label of ['Dashboard','Health','Fitness','Calendar','Discover','Documents','Talk to ZEKE'])assert(nav.includes(label),`${label} missing from navigation`);
for(const label of ["['labs','Labs'","['medications','Medications'","['life-events','Life & Symptoms'","['measurements','Measurements'"])assert(!nav.includes(label),`${label} must not be a global navigation peer`);
assert(nav.includes("Question${questions===1?'':'s'} for You"));assert(app.includes('<h1>Questions for You</h1>'));
assert(app.includes('zeke-user-profile'));assert(!app.includes('Good evening, Frank'));assert(!app.includes('Good morning, Frank'));
console.log('PASS navigation, actionable coaching, profile, and Discover hierarchy');
