const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const must=(x,m)=>{if(!x)throw new Error(m)};
const state=JSON.parse(read('DEVELOPMENT_MEMORY/PROJECT_STATE.json')),gate=JSON.parse(read('DEVELOPMENT_MEMORY/DEVELOPMENT_GATE.json')),index=read('index.html'),version=read('version.js'),sw=read('sw.js');
must(state.current_version==='0.40.0'&&state.current_build==='2026.08.03.1','project state metadata mismatch');
must(gate.current_version==='0.40.0'&&gate.current_iteration.user_approved_scope===true,'development gate mismatch');
must(index.includes('<title>ZEKE v0.40.0</title>')&&index.includes('v0.40.0 · build 2026.08.03.1'),'startup metadata mismatch');
must(version.includes("build: '2026.08.03.1'")&&sw.includes('20260803.1'),'runtime/cache metadata mismatch');
const tokenCount=(index.match(/v=20260803\.1/g)||[]).length;must(tokenCount>=10,'runtime files do not share cache token');
const order=['data-layer.js','parser.js','ai-router.js','workflow-engine.js','exercise-guides.js','knowledge-base.js','integrity-engine.js','app.js'];for(let i=1;i<order.length;i++)must(index.indexOf(order[i-1])<index.indexOf(order[i]),`runtime load order wrong: ${order[i-1]} before ${order[i]}`);
console.log(JSON.stringify({ok:true,version:state.current_version,build:state.current_build,cache_tokens:tokenCount},null,2));
