const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const assert=(v,m)=>{if(!v)throw new Error(m)};
const index=read('index.html'),app=read('assets/app.js'),data=read('assets/data-layer.js'),start=read('00_AI_START_HERE.md');
const state=JSON.parse(read('DEVELOPMENT_MEMORY/PROJECT_STATE.json'));
const gate=JSON.parse(read('DEVELOPMENT_MEMORY/DEVELOPMENT_GATE.json'));
const cacheToken='20260720.1';
assert(index.includes(`<title>ZEKE v${state.current_version}</title>`),'index version missing');
assert(index.includes(`v${state.current_version} · build ${state.current_build}`),'index build missing');
assert(!index.includes('v=20260717.7'),'stale cache-busting token remains');
assert((index.match(new RegExp(`v=${cacheToken}`,'g'))||[]).length>=7,'active assets do not share the release cache-busting token');
assert((app.match(/syncConnectedWorkbook\(/g)||[]).length===2,'connected sync is invoked outside its definition and reviewed commit handler');
assert(app.includes("['taken','administered','completed']"),'medication action completion allowlist missing');
assert(app.includes('\\b(pains|aches|symptoms)\\b'),'concept word-boundary repair missing');
assert(app.includes('replace(/\\b\\w/g'),'activity capitalization word-boundary repair missing');
assert(!Buffer.from(app).includes(8),'literal backspace control character remains in app.js');
assert(data.includes('previousSourceBackupPath=`imports/backups/source-workbook-'),'source replacement archival backup missing');
assert(data.includes('async function verifySourceEvents'),'persisted repository verification missing');
assert(start.includes('Fast orientation'),'fast orientation missing');
assert(start.includes('Historian'),'historian phase missing');
assert(start.includes('Anti-wandering constraints'),'anti-wandering rules missing');
assert(state.current_version&&state.current_build,'project state version missing');
assert(gate.current_iteration.user_approved_scope===true&&gate.current_iteration.prior_conversations_reviewed===true,'development gate is incomplete');
console.log(JSON.stringify({ok:true,cache_tokens:(index.match(new RegExp(`v=${cacheToken}`,'g'))||[]).length,sync_references:(app.match(/syncConnectedWorkbook\(/g)||[]).length},null,2));
