const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
const data=fs.readFileSync(path.join(root,'assets/data-layer.js'),'utf8');
const parser=fs.readFileSync(path.join(root,'assets/parser.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');
const must=(x,m)=>{if(!x)throw new Error(m)};
const ctx={window:{},console,Date,Intl,JSON,Math,Number,String,Object,Array,Map,Set,RegExp};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(parser,ctx);
const parsed=ctx.ZekeParser.interpret('i slept well last night. from approximately 2am on 7/19 to 10:45am 7/19',{now:'2026-07-20T01:00:00-04:00'});
must(parsed.events.length===1,'sleep parser should create one event');
const sleep=parsed.events[0];
must(sleep.category==='sleep','sleep must be a first-class event');
must(sleep.structured.metric_id==='sleep_duration','sleep metric missing');
must(Math.abs(sleep.structured.value-8.75)<0.001,'sleep duration should be 8.75 hours');
must(sleep.structured.sleep_quality==='good','sleep quality missing');
must(sleep.structured.event_date==='2026-07-19','sleep event date should use wake-up date');
must(sleep.structured.wake_date===sleep.structured.event_date,'wake_date and event_date must agree');
must(app.includes("state.pending?.type==='confirm' && affirmativeReply(text)"),'pending confirmation must intercept typed affirmative replies');
must(app.includes('savePendingConfirmed'),'atomic pending-save helper missing');
must(app.includes('<h2>Log sleep</h2>'),'Sleep direct log form missing');
for(const token of ["clockSelects('sleepStart'","clockSelects('sleepEnd'",'${prefix}Hour','${prefix}Minute','${prefix}AmPm','sleepQuality','sleepInterruptions','editSleepStart','editSleepEnd','editSleepQuality','editSleepInterruptions'])must(app.includes(token),`${token} missing from sleep create/edit flow`);
must(app.includes("['measurement','lab','sleep','medication"),'Recent Health Record must explicitly include sleep');
must(app.includes('Recent Health Record'),'Recent Health Record heading missing');
must(css.includes('.time-select-group'),'sleep pull-down styling missing');
must(css.includes('font-size:16px!important'),'mobile anti-zoom form sizing missing');
must(app.includes('potential_health_event'),'Potential Health Events support missing');
must(app.includes('potential_health_events:potentialHealthEvents()'),'Potential Health Events missing from AI packet/context');
must(app.includes('activityChartDescriptor'),'activity graph descriptor missing');
must(app.includes('activity-chart-label')&&css.includes('.activity-chart-status'),'activity graph label/explanation support missing');
for(const id of ['activityRpe','editWorkoutRpe','activityPainBefore','editWorkoutPainBefore','editWorkoutPainDuring','activityPainAfter','editWorkoutPainAfter','editWorkoutTechnique','editWorkoutInjury'])must(app.includes(id),`${id} missing from workout entry/edit schema`);
must(app.includes('Confirm this sleep entry'),'concrete sleep review title missing');
must(!app.includes('Exercise parsing opportunity'),'internal parsing language leaked into app output');
must(data.includes('async function undoEvents'),'undo support missing');
console.log(JSON.stringify({ok:true,sleep_hours:sleep.structured.value,checks:27},null,2));
