const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const assert=(v,m)=>{if(!v)throw new Error(m)};
const index=read('index.html'),app=read('assets/app.js'),css=read('assets/styles.css'),architecture=read('ARCHITECTURE.md');
assert(index.indexOf('assets/workflow-engine.js')<index.indexOf('assets/app.js'),'workflow engine must load before app');
assert(app.includes('Diagnostics & Exports')&&app.includes('Download Support & Improvement Report'),'support export missing from Settings');
for(const tab of ['Executive Summary','Technical Errors','Unresolved Interactions','AI Consultation History','User Corrections','UX Feedback','Potential Health Events','Audit History','Conversation Metrics','Workflow History','Developer Notes'])assert(app.includes(`'${tab}'`)||app.includes(tab),`support tab missing: ${tab}`);
assert(app.includes('Conversation Memory')&&app.includes('Waiting for You')&&app.includes('Things I’ve Learned'),'conversation memory tabs missing');
for(const section of ['Original information','ZEKE’s understanding','Proposed record or action','Why it matters','What ZEKE will do'])assert(app.includes(section),`review section missing: ${section}`);
assert(app.includes('They moved in the same direction')&&app.includes('They moved in opposite directions'),'direction-neutral pattern wording missing');
assert(app.includes('Nothing has been saved yet.')&&app.includes('No structured record was changed.'),'closure status language missing');
assert(app.includes('openMedicationScheduleModal')&&app.includes('Save medication schedule'),'medication schedule editor missing');
assert(app.includes('openRecurringActionScheduleModal')&&app.includes('Save recurring schedule'),'generic recurring-action schedule editor missing');
assert(app.includes('async function deferQuestion')&&app.includes('moved behind newer questions'),'Later must preserve questions instead of resolving them');
assert(app.includes('Your earlier workflow is still open:')&&app.includes('data-resume-workflow'),'restored workflow resume affordance missing');
assert(app.includes("['xlsx','xls','json','csv','tsv'].includes(ext)"),'Talk attachment routing missing');
assert(css.includes('v0.24.0 Trust, Conversation & Workflow')&&css.includes('.workflow-status')&&css.includes('.memory-tabs'),'v0.24 styles missing');
assert(/authoritative runtime/i.test(architecture)&&/legacy/i.test(architecture)&&/no compilation step/i.test(architecture),'architecture does not clarify static runtime and legacy assets');
console.log(JSON.stringify({ok:true,checks:14},null,2));
