const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const app=read('assets/app.js'),kb=read('assets/knowledge-base.js'),css=read('assets/styles.css'),index=read('index.html'),version=read('version.js');
const must=(v,m)=>{if(!v)throw new Error(m)};
must(index.includes('ZEKE v0.41.0')&&version.includes("build: '2026.08.07.1'"),'v0.41 identity missing');
for(const field of ['exercise_family','variation_name','equipment_type','load_basis','identity_schema_version'])must(app.includes(field),`exercise identity field missing: ${field}`);
must(app.includes('openExerciseIdentityReviewModal')&&app.includes('Leave equipment / variation unspecified'),'non-destructive historical identity review missing');
must(app.includes('activityRecommendation')&&app.includes('RPE')&&app.includes('RIR')&&app.includes('Why / evidence'),'progressive overload logger/evidence missing');
must(app.includes('data-dashboard-range')&&app.includes('dashboardHealthRange')&&app.includes('dashboardTrendRange'),'section-owned dashboard ranges missing');
must(!/class="range-tabs"/.test(app.split('function topbarHTML')[1]?.split('function')[0]||''),'detached dashboard topbar range remains');
must(app.includes('discoveryCards')&&app.includes('Explore all patterns')&&app.includes('weak/trivial candidates hidden'),'Discover integrated pattern screening missing');
must(app.includes('activityPatternMeta')&&app.includes('conceptualPair'),'pattern semantic filtering missing');
must(app.includes('recentWindowDays')&&app.includes('metricRecentInsight'),'recent-oriented trend analysis missing');
must(app.includes('duplicateReviewHTML')&&app.includes('Same event — keep one')&&app.includes('These are separate events'),'plain-language duplicate review missing');
must(app.includes("adherence_mode==='assume_scheduled'")&&app.includes('scheduled-adherence-assumption')&&app.includes('assumption_rule'),'scheduled adherence assumption missing');
for(const name of ['Side-Lying External Rotation (S/L ER)','Shoulder Internal Rotation — Resistance Band (IR)','Scaption (scaption)','Posterior Capsule Stretch (post cap stretch)','PNF Shoulder Diagonal 1 (D1)','PNF Shoulder Diagonal 2 (D2)'])must(kb.includes(name),`PT guide missing: ${name}`);
must(!kb.includes('\"K ER\"')&&!kb.includes('\"K IR\"'),'uncertain PT shorthand K ER/K IR must not be asserted');
must(kb.includes('External_Rotation_with_Band/0.jpg')&&kb.includes('External_Rotation/0.jpg'),'verified ER media mappings missing');
must(kb.includes('Dumbbell_Scaption/0.jpg')&&kb.includes('Shoulder_Stretch/0.jpg'),'verified PT recognition media mappings missing');
must(css.includes('v0.41.0 — Fitness Intelligence & Clarity'),'v0.41 styles missing');
console.log(JSON.stringify({ok:true,checks:17},null,2));
