const fs=require('fs');
const read=f=>fs.readFileSync(f,'utf8');
const app=read('assets/app.js'),css=read('assets/styles.css'),training=read('assets/training-intelligence.js'),anatomy=read('assets/anatomy-knowledge.js'),version=read('version.js'),index=read('index.html'),mobile=read('assets/mobile-polish-v0441.js');
const must=(x,m)=>{if(!x)throw new Error(m)};
must(version.includes("version: '0.46.0'")&&version.includes("build: '2026.08.24.1'"),'v0.46 runtime identity missing');
must(index.includes('anatomy-knowledge.js')&&index.indexOf('anatomy-knowledge.js')<index.indexOf('app.js'),'anatomy registry not loaded before app');
must(app.includes('dashboard-v46')&&css.includes('.dashboard-v46-top'),'purpose-driven dashboard composition missing');
must(app.includes('recent-activity-scroll')&&css.includes('max-height:420px'),'recent activity scan window missing');
must(app.includes('globalTalkClose')&&app.includes('global-talk-expanded')&&css.includes('.global-talk-close'),'Talk to ZEKE close/expand interaction missing');
must(app.includes('review-live-feedback')&&app.includes("el.textContent='Saving…'"),'review decision feedback missing');
must(app.includes('data-body-browse')&&app.includes('Search (optional)'),'browse-first exercise navigation missing');
must(app.includes('bodyAreaLinksHTML')&&app.includes('bodyAreaInjuryMatches'),'body area / injury linkage missing');
must(anatomy.includes('review_interval_days')&&anatomy.includes('packStatus')&&anatomy.includes('anatomyForExercise'),'versioned anatomy knowledge mechanism missing');
must(app.includes('variationSummaryHTML')&&app.includes('sets')&&app.includes('data-variation-focus'),'variation detail/focus missing');
must(app.includes('familyVariationChart')&&app.includes('Separate lines · shared axes'),'variation-aware shared axes chart missing');
must(training.includes('WHY THIS CAN HELP')&&training.includes('See the context ZEKE will use'),'short why / deeper reasoning pattern missing');
must(mobile.includes('window.ZEKE_BUILD'),'mobile build label must derive from runtime authority');
must(!mobile.includes("v0.44.1 · build 2026.08.18.1"),'stale mobile build string remains');
console.log(JSON.stringify({ok:true,release:'0.46.0',checks:14},null,2));
