const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const must=(x,m)=>{if(!x)throw new Error(m)};
const app=read('assets/app.js'),training=read('assets/training-intelligence.js'),version=read('version.js'),constitution=read('ZEKE_CONSTITUTION.md'),scope=read('CURRENT_RELEASE_SCOPE.md'),sw=read('sw.js'),index=read('index.html');
must(version.includes("version: '0.48.0.2'")&&version.includes("build: '2026.08.30.1'"),'unique runtime identity missing');
must(sw.includes('project-zeke-v0.48.0.2-2026.08.30.1'),'unique service-worker cache identity missing');
must(index.includes('v0.48.0.2 · build 2026.08.30.1'),'startup identity missing');
must(app.includes("timelineScale:localStorage.getItem('zeke.timeline.scale.v1')||'week'"),'timeline scale state missing');
for(const scale of ['day','week','month','year'])must(app.includes(`['${scale}','${scale[0].toUpperCase()+scale.slice(1)}']`),'timeline scale missing: '+scale);
must(app.includes('sleepPeriodAnalysis')&&app.includes('previousWeek')&&app.includes('prev30')&&app.includes('avg90'),'sleep period comparison engine missing');
must(app.includes('data-timeline-event')&&app.includes('editEvent(id)'),'timeline records are not clickable');
must(app.includes('data-body-area')&&app.includes('data-open-body-exercise'),'body/exercise bidirectional exploration missing');
must(/## 83\. Distinct distributed builds/.test(constitution),'unique-version constitutional rule missing');
must(/## 85\. No universal readiness score/.test(constitution),'no-readiness-score rule missing');
must(training.includes('\"session_status\":\"proceed|modify|insufficient_context\"')&&!training.includes('\"readiness\"'),'workout AI contract still exposes readiness');
must(!constitution.includes('Readiness is qualitative and evidence-bounded')&&!constitution.includes('numberless visual gauge may provide'),'active Constitution still permits a readiness-gauge substitute');
must(/## 86\. No social or community product layer/.test(constitution),'no-social/community rule missing');
must(/## 87\. Connected entities are explorable/.test(constitution),'connected exploration rule missing');
must(scope.includes('week vs prior week')&&scope.includes('30d vs prior 30d'),'trend-first sleep acceptance scope missing');
console.log(JSON.stringify({ok:true,release:'0.48.0.2',checks:16},null,2));
